version: '3'

services:
   elasticsearch:
      build:
         context:
            ./elasticsearch
         dockerfile:
            Dockerfile
      container_name:
         docker-elasticsearch
      volumes:
         - ./elasticsearch/data:/usr/share/elasticsearch/data
      ports:
         - "9200:9200"
      environment:
         ES_JAVA_OPTS: "-Xmx256m -Xms256m"
         xpack.security.enabled: "false"
         xpack.monitoring.enabled: "false"
         xpack.graph.enabled: "false"
         xpack.watcher.enabled: "false"
      networks:
         - elknet

   logstash:
      build:
         context:
            ./logstash
         dockerfile:
            Dockerfile
      container_name:
         docker-logstash
      volumes:
         - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
         - ./logstash/pipeline:/usr/share/logstash/pipeline
      ports:
         - "5044:5044" # filebeat input
      environment:
         ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      networks:
         - elknet
      depends_on:
         - elasticsearch

   filebeat:
      build:
         context:
            ./filebeat
         dockerfile:
            Dockerfile
      container_name:
         docker-filebeat
      volumes:
         - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
         - ./filebeat/data:/mnt/data
      networks:
         - elknet
      depends_on:
         - elasticsearch
         - logstash

   kibana:
      build:
         context:
            ./kibana
         dockerfile:
            Dockerfile
      container_name:
         docker-kibana
      volumes:
         - ./kibana/config:/usr/share/kibana/config
      ports:
         - "5601:5601"
      networks:
         - elknet
      depends_on:
         - elasticsearch

networks:
   elknet:
      driver: bridge
